Add editable landing page Docs and Sales Training components
deco-sites/starting pull request #166
Opened 2023-08-28 15:15 UTC by devartes

2023-08-28 20:17 UTC, matheusgr requested changes

2023-08-28 21:01 UTC, devartes commented on components/decohelp/pages/ui/WasThisPageHelpful/WasThisPageHelpful.tsx
> +      Yes?: string;
![image](https://github.com/deco-sites/starting/assets/76822093/a238ed04-9883-426b-b0f3-3c24f8b68b8a)
Modificado

2023-08-28 21:01 UTC, devartes commented on components/decohelp/pages/ui/WasThisPageHelpful/WasThisPageHelpful.tsx
> +      No?: string;
![image](https://github.com/deco-sites/starting/assets/76822093/e1b0a5c6-1f2d-4a0c-94b2-fd87b8285d7d)
modificado

2023-08-28 21:04 UTC, devartes commented on components/decohelp/pages/ui/WasThisPageHelpful/WasThisPageHelpful.tsx
> +                </figure>
![image](https://github.com/deco-sites/starting/assets/76822093/d8d6fb8f-1e5d-4115-845d-488865becb66)
![image](https://github.com/deco-sites/starting/assets/76822093/8d751f4d-8beb-4fae-b5d2-1794dfa355e5)

modificado: a imagem agora só é exibida se existir uma.

2023-08-28 21:06 UTC, devartes commented on components/decohelp/pages/ui/WasThisPageHelpful/WasThisPageHelpful.tsx
> +          <HTMLRenderer html={text} />
![image](https://github.com/deco-sites/starting/assets/76822093/89d90194-98fd-4b91-bb84-a58b8928d1c7)
![image](https://github.com/deco-sites/starting/assets/76822093/a0e7fc19-612d-44be-8e42-e681239aad3c)
aqui aparece pra mim

2023-08-28 22:18 UTC, devartes commented on components/decohelp/pages/interfaces.ts
> +}
![image](https://github.com/deco-sites/starting/assets/76822093/d91495e6-97ae-4e4a-9eb2-d7ba39218847)
modificado

2023-08-29 12:21 UTC, matheusgr approved these changes

2023-08-29 12:22 UTC, merged